services:
  - type: web
    name: flower-classification-api
    env: python
    pythonVersion: 3.10
    rootDir: backend
    buildCommand: pip install -r ./requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production